
version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: titanic
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./titanic_passengers.csv:/var/lib/mysql-files/titanic.csv

  api-service:
    build: ./api-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  web-frontend:
    build: ./web-frontend
    ports:
      - "80:80"
    depends_on:
      - api-service

volumes:
  db_data:
