version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: titanic
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --secure-file-priv=/var/lib/mysql-files
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./titanic_passengers.csv:/var/lib/mysql-files/titanic.csv

  api-service:
    build: ./api-service
    ports:
      - "5000:5000"
    depends_on:
      - db

  web-frontend:
    build: ./web-frontend
    ports:
      - "80:80"
    depends_on:
      - api-service

volumes:
  db_data:
